version: '3.8'

services:
  
  postgres_db:
    restart : always
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_PASSWORD: '*****' # password of database 
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./src/common/db.sql:/docker-entrypoint-initdb.d/db.sql

  e_commerce:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    networks:
      - app-network
    volumes:
      - ./src:/app/src
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres_db
      POSTGRES_DB: ecommerce_db
      POSTGRES_PASSWORD: '****'
      POSTGRES_PORT: 5432
    depends_on:
      - postgres_db

  pgAdmin:
    image: dpage/pgadmin4
    environment:
       PGADMIN_DEFAULT_EMAIL: admin@example.com
       PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15433:80"
    depends_on:
      - postgres_db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge






